import { StyleSheet } from "react-native";
import {
  BLACK,
  GRAY,
  PRIMARY_DARK,
  PRIMARY_LIGHT,
  WHITE,
} from "../../../styles/colors";

export const styles = StyleSheet.create({
  mainContent: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    alignItems: "center",
  },
  title: {
    fontSize: 24,
    fontFamily: "Gilroy-ExtraBold",
    color: PRIMARY_DARK,
    marginVertical: 25,
  },
  normalInfoContent: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    marginBottom: 10,
    maxWidth: "100%",
    minWidth: "80%",
    paddingHorizontal: 40,
  },
  avatar: {
    width: 100,
    height: 100,
    marginRight: 10,
  },
  normalInfo: {
    display: "flex",
    justifyContent: "center",
    flexWrap: "wrap",
    flexDirection: "column",
  },
  name: {
    fontFamily: "Poppins-Bold",
    fontSize: 18,
    color: BLACK,
    maxWidth: "90%",
    minWidth: "90%",
  },
  groupInfo: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: WHITE,
    marginBottom: 2,
    padding: 10,
    borderRadius: 20,
    maxWidth: "90%",
    minWidth: "90%",
  },
  labelInfo: {
    fontFamily: "Poppins-Light",
    flexWrap: "wrap",
    fontSize: 14,
    color: GRAY,
  },
  valueInfo: {
    fontFamily: "Poppins-Bold",
    fontSize: 14,
    flexWrap: "wrap",
    color: BLACK,
  },
  extraInfoContent: {
    display: "flex",
    justifyContent: "flex-start",
    flexDirection: "column",
    alignItems: "flex-start",
    maxWidth: "90%",
    minWidth: "90%",
  },
  contentScrollView: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    marginHorizontal: 10,
    paddingVertical: 15,
  },
  itemAccess: {
    width: 140,
    height: 140,
    display: "flex",
    marginHorizontal: 10,
    backgroundColor: PRIMARY_DARK,
    justifyContent: "center",
    flexDirection: "column",
    alignItems: "center",
    borderTopStartRadius: 15,
    borderTopEndRadius: 15,
    borderBottomStartRadius: 15,
    borderBottomEndRadius: 15,
  },
  containerIcon: {
    backgroundColor: PRIMARY_LIGHT,
    padding: 12,
    borderTopStartRadius: 150,
    borderTopEndRadius: 150,
    borderBottomStartRadius: 150,
    borderBottomEndRadius: 150,
  },
  nameItem: {
    textAlign: "center",
    marginTop: 10,
    fontFamily: "Poppins-Regular",
    fontSize: 18,
    color: PRIMARY_LIGHT,
  },
});
